# Generated by Django 4.1.7 on 2023-02-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
