# Generated by Django 4.1.7 on 2023-02-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_historico_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='identificador',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
