# Generated by Django 4.1.7 on 2023-02-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_historico_identificador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(max_length=10)),
                ('p2', models.CharField(max_length=10)),
                ('p3', models.CharField(max_length=10)),
                ('p4', models.CharField(max_length=10)),
                ('p5', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='historico',
            name='minute',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
