# Generated by Django 4.1.7 on 2023-09-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_sequencia_historico_minute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_telegram', models.CharField(max_length=2000)),
                ('id_sala_telegram', models.CharField(max_length=200)),
            ],
        ),
    ]
